### ISSUE TITLE
WARNI [fpdf.html] Unexpected HTML end tag </head>, start tag was <meta>

### ISSUE THREAD

**Issue by erickellerek1** [open-webui/open-webui#7546]
# Bug Report

## Installation Method

Docker following the readme instructions.
```
docker run -d -p 3000:8080 --add-host=host.docker.internal:host-gateway -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:dev
```

## Environment

- **Open WebUI Version:**: v0.4.7 (main or dev)
- **Ollama (if applicable):** v0.4.7

- **Operating System:** Ubuntu 24.04
- **Browser (if applicable):** Chrome 131.0

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

following the instructions
![image](https://github.com/user-attachments/assets/53a0dcbc-32c0-44c8-9867-30ac84702239)

I expect to have a PDF generated and starting to download.

## Actual Behavior:

There is no PDF downloaded, the action fails silently in the background, no information of failure is displayed to the user.

**Bug Summary:**

using downloads tools to export a chat is not working and silently fails in the background, no message of failure is written back to the user.

## Reproduction Details

**Steps to Reproduce:**

go to tools -> Downloads -> pdf

## Logs and Screenshots

**Browser Console Logs:**

![image](https://github.com/user-attachments/assets/21be7678-305d-4663-ab6f-29332b135570)

**Docker Container Logs:**

`docker logs -f open-webui`
```
INFO:     10.146.92.13:28982 - "GET /api/v1/chats/8eb3414c-8c90-43ea-88cf-2226e8f5f4f4/tags HTTP/1.1" 200 OK
WARNI [fpdf.html] Unexpected HTML end tag </head>, start tag was <meta>
Character "’" at index 271 in text is outside the range of characters supported by the font used: "courier". Please consider using a Unicode font.
INFO:     10.146.92.13:28982 - "POST /api/v1/utils/pdf HTTP/1.1" 400 Bad Request
```

**Screenshots/Screen Recordings (if applicable):**
N.A.

## Additional Information

the font I use on the browser are: hack as default I am not sure this has any impact on the error message.
![image](https://github.com/user-attachments/assets/e8b6f4b2-5407-4db6-85b7-3ad5b69a6d08)

## Note

related issue: https://github.com/open-webui/open-webui/issues/5737

**Comment by tjbck** [comment]
#7684
